# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
net.minecraftforge.gradle.merge-source-sets=true

# Forge Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
forge_version=52.1.14
forge_version_range=[52,)
loader_version_range=[52,)
java_version=21

# Mod Properties
mod_id=attuned
mod_name=Attuned
mod_license=MIT
mod_version=1.5.7+forge.mc1.21.1
maven_group=dev.attuned
mod_authors=defnotean
mod_description=An attunement-economy accessory framework. Equip Foci into inventory slots and spend a limited attunement budget on their effects.
