modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/defnotean/attuned/issues"

[[mods]]
modId="attuned"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/defnotean/attuned"
logoFile="assets/attuned/icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="attuned.mixins.json"

[[mixins]]
config="attuned.client.mixins.json"

[[dependencies.attuned]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.attuned]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.attuned]]
modId="lootr"
type="optional"
versionRange="*"
ordering="NONE"
side="BOTH"

[features.attuned]
javaVersion="[${java_version},)"
