"""Contract for the deterministic Attunement Sanctum NBT template generator.

The generator (``tools/generate_sanctum_template.py``) hand-rolls a gzipped,
big-endian NBT structure template using only the standard library, mirroring the
hand-rolled PNG encoder in ``tools/verify_repository.py``. These tests assert the
generated bytes describe a valid 15x8x15 sanctum with the expected palette and a
single loot chest, that the ``DataVersion`` is read from a real vanilla template
fixture rather than hardcoded, and that the output is byte-identical run to run.
"""

from __future__ import annotations

import gzip
import importlib.util
import json
import struct
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "tools" / "generate_sanctum_template.py"

spec = importlib.util.spec_from_file_location("generate_sanctum_template", MODULE_PATH)
generate_sanctum_template = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(generate_sanctum_template)


# --- A minimal big-endian NBT reader (tag ids 0-12). --------------------------
class _NbtReader:
    def __init__(self, data: bytes) -> None:
        self._data = data
        self._pos = 0

    def _take(self, count: int) -> bytes:
        chunk = self._data[self._pos : self._pos + count]
        self._pos += count
        return chunk

    def _u8(self) -> int:
        return struct.unpack(">B", self._take(1))[0]

    def _i16(self) -> int:
        return struct.unpack(">h", self._take(2))[0]

    def _i32(self) -> int:
        return struct.unpack(">i", self._take(4))[0]

    def _i64(self) -> int:
        return struct.unpack(">q", self._take(8))[0]

    def _f32(self) -> float:
        return struct.unpack(">f", self._take(4))[0]

    def _f64(self) -> float:
        return struct.unpack(">d", self._take(8))[0]

    def _string(self) -> str:
        length = struct.unpack(">H", self._take(2))[0]
        return self._take(length).decode("utf-8")

    def _payload(self, tag_id: int):
        if tag_id == 0:  # TAG_End
            return None
        if tag_id == 1:  # TAG_Byte
            return self._u8()
        if tag_id == 2:  # TAG_Short
            return self._i16()
        if tag_id == 3:  # TAG_Int
            return self._i32()
        if tag_id == 4:  # TAG_Long
            return self._i64()
        if tag_id == 5:  # TAG_Float
            return self._f32()
        if tag_id == 6:  # TAG_Double
            return self._f64()
        if tag_id == 7:  # TAG_Byte_Array
            length = self._i32()
            return list(self._take(length))
        if tag_id == 8:  # TAG_String
            return self._string()
        if tag_id == 9:  # TAG_List
            item_id = self._u8()
            length = self._i32()
            return [self._payload(item_id) for _ in range(length)]
        if tag_id == 10:  # TAG_Compound
            compound: dict = {}
            while True:
                child_id = self._u8()
                if child_id == 0:
                    break
                name = self._string()
                compound[name] = self._payload(child_id)
            return compound
        if tag_id == 11:  # TAG_Int_Array
            length = self._i32()
            return [self._i32() for _ in range(length)]
        if tag_id == 12:  # TAG_Long_Array
            length = self._i32()
            return [self._i64() for _ in range(length)]
        raise ValueError(f"unknown tag id {tag_id}")

    def read_root(self) -> dict:
        root_id = self._u8()
        self._string()  # root name (empty)
        return self._payload(root_id)


def _read_template(raw: bytes) -> dict:
    return _NbtReader(gzip.decompress(raw)).read_root()


# Minimal vanilla template fixture: a gzipped root compound carrying only the
# DataVersion the generator must echo. Big-endian, ints are tag id 3.
FIXTURE_DATA_VERSION = 4790


def _write_fixture(path: Path, data_version: int) -> None:
    body = b"\x0a\x00\x00"  # TAG_Compound, empty name
    body += b"\x03" + struct.pack(">H", len("DataVersion")) + b"DataVersion"
    body += struct.pack(">i", data_version)
    body += b"\x00"  # TAG_End
    path.write_bytes(gzip.compress(body))


class SanctumTemplateContractTest(unittest.TestCase):
    def test_default_vanilla_path_uses_active_profile_and_common_jar_first(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_root = Path(temp_dir) / "repo"
            temp_home = Path(temp_dir) / "home"
            (temp_root / "config").mkdir(parents=True)
            (temp_root / "config" / "minecraft-version-profiles.json").write_text(
                json.dumps({
                    "active_profile": "26.2",
                    "profiles": {"26.2": {"minecraft_version": "26.2"}},
                }),
                encoding="utf-8",
            )
            common = (
                temp_home / ".gradle" / "caches" / "fabric-loom" / "minecraftMaven"
                / "net" / "minecraft" / "minecraft-common-deobf" / "26.2"
                / "minecraft-common-deobf-26.2.jar"
            )
            common.parent.mkdir(parents=True)
            common.write_bytes(b"jar placeholder")

            self.assertEqual(
                generate_sanctum_template.active_minecraft_version(temp_root),
                "26.2",
            )
            self.assertEqual(
                generate_sanctum_template.default_vanilla_path(temp_root, temp_home),
                common,
            )

    def test_data_version_is_read_from_fixture_not_hardcoded(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            fixture = Path(temp_dir) / "vanilla.nbt"
            unusual_version = 12345
            _write_fixture(fixture, unusual_version)

            root = _read_template(generate_sanctum_template.build_template(fixture))

            self.assertEqual(root["DataVersion"], unusual_version)

    def test_size_is_15_8_15(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            fixture = Path(temp_dir) / "vanilla.nbt"
            _write_fixture(fixture, FIXTURE_DATA_VERSION)

            root = _read_template(generate_sanctum_template.build_template(fixture))

            self.assertEqual(root["size"], [15, 8, 15])

    def test_palette_includes_signature_blocks(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            fixture = Path(temp_dir) / "vanilla.nbt"
            _write_fixture(fixture, FIXTURE_DATA_VERSION)

            root = _read_template(generate_sanctum_template.build_template(fixture))
            names = {entry["Name"] for entry in root["palette"]}

            self.assertIn("minecraft:chiseled_deepslate", names)
            self.assertIn("minecraft:amethyst_block", names)

    def test_exactly_one_chest_with_sanctum_loot_table(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            fixture = Path(temp_dir) / "vanilla.nbt"
            _write_fixture(fixture, FIXTURE_DATA_VERSION)

            root = _read_template(generate_sanctum_template.build_template(fixture))
            chests = [
                block
                for block in root["blocks"]
                if isinstance(block.get("nbt"), dict)
                and block["nbt"].get("id") == "minecraft:chest"
            ]

            self.assertEqual(len(chests), 1)
            self.assertEqual(chests[0]["nbt"]["LootTable"], "attuned:chests/sanctum")

    def test_no_entities(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            fixture = Path(temp_dir) / "vanilla.nbt"
            _write_fixture(fixture, FIXTURE_DATA_VERSION)

            root = _read_template(generate_sanctum_template.build_template(fixture))

            self.assertEqual(root.get("entities", []), [])

    def test_output_is_byte_identical_across_runs(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            fixture = Path(temp_dir) / "vanilla.nbt"
            _write_fixture(fixture, FIXTURE_DATA_VERSION)

            first = generate_sanctum_template.build_template(fixture)
            second = generate_sanctum_template.build_template(fixture)

            self.assertEqual(first, second)


if __name__ == "__main__":
    unittest.main()
